# Generated by Django 3.0.5 on 2021-05-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyTitle', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Company Title')),
                ('companyName', models.CharField(max_length=250)),
                ('taxOffice', models.CharField(max_length=250)),
                ('taxNumber', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('subsidiaryTitle', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Subsidiary Title')),
                ('subsidiaryName', models.CharField(blank=True, max_length=250)),
                ('sub_taxOffice', models.CharField(max_length=250)),
                ('sub_taxNumber', models.IntegerField()),
                ('sub_tel', models.IntegerField()),
                ('sub_email', models.EmailField(max_length=150)),
                ('sub_address', models.CharField(max_length=500)),
                ('companyName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company')),
            ],
            options={
                'db_table': 'Subsidiary',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
