# Generated by Django 3.0.5 on 2021-05-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidiary',
            name='companyName',
        ),
    ]
