# Generated by Django 3.0.5 on 2021-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_subsidiary_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='taxNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='sub_taxNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='sub_tel',
            field=models.CharField(max_length=100),
        ),
    ]
