# Generated by Django 3.0.5 on 2021-05-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210511_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='companyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company'),
        ),
    ]
