# Generated by Django 3.0.5 on 2021-05-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_subsidiary_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companyTitle',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subsidiary',
            old_name='subsidiaryTitle',
            new_name='id',
        ),
    ]
