# Generated by Django 3.0.5 on 2021-05-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210511_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id',
            new_name='companyTitle',
        ),
        migrations.RenameField(
            model_name='subsidiary',
            old_name='id',
            new_name='subsidiaryTitle',
        ),
    ]
