# Generated by Django 2.2.19 on 2021-06-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='id',
            new_name='form_id',
        ),
    ]
