# Generated by Django 2.2.19 on 2021-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210608_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(auto_created=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
