# Generated by Django 2.2.19 on 2021-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210608_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
